spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ServiceTech
    username: ${username}
    password: ${password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
